export interface GameTheme {
  id: number;
  name: string;
  freeSpaceLabel?: string;
  labels: string[];
}

export const MOCK_GAME_THEMES: GameTheme[] = [
  {
    id: 0,
    name: "Steelheads Hockey Jerseys",
    freeSpaceLabel: "Steelheads",
    labels: [
      "Anaheim Ducks",
      "Arizona Coyotes",
      "Boston Bruins",
      "Buffalo Sabres",
      "Calgary Flames",
      "Carolina Hurricanes",
      "Chicago Blackhawks",
      "Colorado Avalanche",
      "Columbus Blue Jackets",
      "Dallas Stars",
      "Detroit Red Wings",
      "Edmonton Oilers",
      "Florida Panthers",
      "Los Angeles Kings",
      "Minnesota Wild",
      "Montreal Canadiens",
      "Nashville Predators",
      "New Jersey Devils",
      "New York Islanders",
      "New York Rangers",
      "Ottawa Senators",
      "Philadelphia Flyers",
      "Pittsburgh Penguins",
      "San Jose Sharks",
      "Seattle Kraken",
      "St. Louis Blues",
      "Tampa Bay Lightning",
      "Toronto Maple Leafs",
      "Vancouver Canucks",
      "Vegas Golden Knights",
      "Washington Capitals",
      "Winnipeg Jets",
      "Fictional Team",
      "Historic Team",
      "College Team",
      "AHL/ECHL",
    ],
  },
  {
    id: 1,
    name: "Baseball",
    labels: [
      "Strikeout (swinging)",
      "Strikeout (looking)",
      "Single",
      "Double",
      "Triple",
      "Home Run",
      "Walk",
      "Hit by Pitch",
      "Sacrifice Fly",
      "Sacrifice Bunt",
      "Stolen Base",
      "Caught Stealing",
      "Diving Catch",
      "Double Play",
      "Triple Play",
      "Ground Rule Double",
      "Wild Pitch",
      "Passed Ball",
      "Infield Fly Rule",
      "Pop-up to catcher",
      "Dropped Third Strike",
      "Pitcher Pickoff Attempt",
      "Relief Pitcher Enters",
      "Mound Visit",
      "Player or Coach Ejected",
      "Batter Breaks Bat",
      "Runner Slides into Base",
      "Replay Review",
      "Balk",
      "Fan Interference",
      "Rain Delay",
      "Player Loses a Helmet",
      "Foul Ball Into Dugout",
      "Ball Hits Umpire",
      "Player argues with the umpire",
      "Fan Catches Foul Ball",
      "Mascot Does Something Weird",
      "Wave in the Crowd",
      "Fan on Jumbotron Doing a Dance",
    ],
  },
  {
    id: 2,
    name: "Brewery People Watching",
    labels: [
      "Train",
      "Something Falls",
      "Broken Glass",
      "Bike Gear Inside",
      "Hat from a different Brewery",
      "Shirt from a different Brewery",
      "Actively Brewing",
      "Staff Drinking",
      "Beard Over 6 Inches",
      "Board Game Being Played",
      "Laptop Out",
      "Food Truck",
      "Small Dog (Under 15 lbs.)",
      "Beer Flight",
      "Unattended Child",
      "Someone Asking for Wine",
      "Dog Wearing a Bandana",
      "Instagram Photo Shoot",
      "Flannel",
      "Lawn Game in Progress",
      "Man Bun",
      "Dog Eating Human Food",
      "Someone Reading a Book",
      "Man Bun",
      "Barking Dog",
      "Large Dog (Over 50 lbs.)",
      "Someone Leaving with Beer to go",
      "Party Bus",
    ],
  },
  {
    id: 3,
    name: "Boise Greenbelt",
    labels: [
      "Barefoot Bicycling",
      "Dog Off Leash",
      "In a Swimsuit, Not Wet",
      "Biking with No Hands",
      "2+ Pieces of BSU Gear",
      "Scooting with Cargo",
      "Someone Playing a Musical Instrument",
      "Dog in a Cart",
      "2+ People on One Vehicle",
      "Surfboard on a Bike",
      "Tie-Dye",
      "Carrying an Inflatable Object",
      "Cowboy Hat",
      "Knee Pads",
      "Roller Skates",
      "Out of Control Children",
      "Screaming Kids",
      "Drinking Something Questionable",
      "Skate Board",
      "Loitering in Middle of the Path",
      "Maintenance Vehicle",
      "People Arguing",
      "Bicycle Cop",
      "One Wheel/Segway",
      "Dog wearing clothes",
    ],
  },
  {
    id: 4,
    name: "Tattoos",
    labels: [
      "Butterfly",
      "Neck tattoo",
      "Matching couple tats",
      "Barbed wire",
      "Script across ribs",
      "Forearm quote",
      "Face tattoo",
      "Wrist infinity symbol",
      "Finger tattoos",
      "Sleeve in progress",
      "Tattoo of an animal",
      "Floral arm piece",
      "Persons Name",
      "Year",
      "Tiny heart or star",
      "Angel wings",
      "Compass or map",
      "Zodiac sign",
      "Roman numerals",
      "Memorial cross",
      "Tattoo behind ear",
      "Tribal design",
      "Tattoo in foreign language",
      "Matching friend tattoos",
      "Pop culture reference",
      "Skull or bones",
      "Tattoo of eyes",
      "Bad Tattoo",
      "Cartoon character",
      "Spelling error",
      "Tattoo on thigh",
    ],
  },
];
