export interface GameTheme {
  id: number;
  name: string;
  freeSpaceLabel?: string;
  labels: string[];
}

export const MOCK_GAME_THEMES: GameTheme[] = [
  {
    id: 0,
    name: "Steelheads Hockey Jerseys",
    freeSpaceLabel: "Steelheads",
    labels: [
      "Anaheim Ducks",
      "Arizona Coyotes",
      "Boston Bruins",
      "Buffalo Sabres",
      "Calgary Flames",
      "Carolina Hurricanes",
      "Chicago Blackhawks",
      "Colorado Avalanche",
      "Columbus Blue Jackets",
      "Dallas Stars",
      "Detroit Red Wings",
      "Edmonton Oilers",
      "Florida Panthers",
      "Los Angeles Kings",
      "Minnesota Wild",
      "Montreal Canadiens",
      "Nashville Predators",
      "New Jersey Devils",
      "New York Islanders",
      "New York Rangers",
      "Ottawa Senators",
      "Philadelphia Flyers",
      "Pittsburgh Penguins",
      "San Jose Sharks",
      "Seattle Kraken",
      "St. Louis Blues",
      "Tampa Bay Lightning",
      "Toronto Maple Leafs",
      "Vancouver Canucks",
      "Vegas Golden Knights",
      "Washington Capitals",
      "Winnipeg Jets",
      "Fictional Team",
      "Historic Team",
      "College Team",
      "AHL/ECHL",
    ],
  },
  {
    id: 1,
    name: "Baseball",
    labels: [
      "Strikeout (swinging)",
      "Strikeout (looking)",
      "Single",
      "Double",
      "Triple",
      "Home Run",
      "Walk (Base on Balls)",
      "Hit by Pitch",
      "Sacrifice Fly",
      "Sacrifice Bunt",
      "Stolen Base",
      "Caught Stealing",
      "Diving Catch",
      "Double Play",
      "Triple Play",
      "Ground Rule Double",
      "Wild Pitch",
      "Passed Ball",
      "Infield Fly Rule",
      "Pop-up to catcher",
      "Dropped Third Strike",
      "Pitcher Pickoff Attempt",
      "Relief Pitcher Enters",
      "Mound Visit",
      "Player or Coach Ejected",
      "Batter Breaks Bat",
      "Runner Slides into Base",
      "Replay Review",
      "Balk Called",
      "Fan Interference",
      "Rain Delay",
      "Player Loses a Helmet",
      "Catcher Backpick Attempt",
      "Foul Ball Into Dugout",
      "Ball Hits Umpire",
      "Player argues with the umpire",
      "Fan Catches Foul Ball",
      "Mascot Does Something Weird",
      "Wave in the Crowd",
      "Fan on Jumbotron Doing a Dance",
    ],
  },
  {
    id: 2,
    name: "Brewery People Watching",
    labels: [
      "Train",
      "Something Falls",
      "Broken Glass",
      "Bike Gear Inside",
      "Dog",
      "Other Brewery Apparel",
      "Actively Brewing",
      "Staff Drinking",
      "Baby in a Beanie",
      "Beard Over 6 Inches",
      "Live Music",
      "Board Game Being Played",
      "Laptop Out",
      "Food Truck",
      "Guy Describing His Homebrew",
      "Group in Matching Shirts",
      "Instagram Photo Shoot",
      "Beer Flight",
      "Someone Asking for Wine",
      "Hazy IPA Discussion",
      "Unattended Child",
      "Patio Heater Even Though It’s Warm",
      "Pretzel Necklace",
      "Someone Wearing Flip Flops in Winter",
      "Corgi or Bulldog",
      "Branded Growler",
      "Awkward First Date",
      "Bachelorette Party",
      "Guy Mansplaining Beer",
      "Dog Wearing a Bandana",
      "Oversized Flannel",
      "Person with Sticker-Covered Hydroflask",
      "Brewery Cat",
      "Lawn Game in Progress",
      "Tie-Dye Shirt",
      "Kid with Headphones",
      "Man Bun",
      "Suspendered Bartender",
      "Smells Like Wort",
      "Vinyl Record Playing",
      "Tiny Beer for Dog in Water Bowl",
    ],
  },
  {
    id: 3,
    name: "Boise Greenbelt",
    labels: [
      "Barefoot Bicycling",
      "Dog Off Leash",
      "In a Swimsuit, Not Wet",
      "Biking with No Hands",
      "2+ Pieces of BSU Gear",
      "Scooting with Cargo",
      "Someone Playing a Musical Instrument",
      "Dog in a Cart",
      "2+ People on One Vehicle",
      "Surfboard on a Bike",
      "Dude with a Tramp Stamp",
      "Rollerblades and a Fanny Pack",
      "Electric Unicycle",
      "Fishing from the Path",
      "Guy with a Giant Backpack for No Reason",
      "Yoga on the Sidewalk",
      "Matching Tie-Dye Outfits",
      "Carrying an Inflatable Object",
      "Walking a Cat",
      "Unexpected Cowboy Hat",
      "Entire Group in Flip-Flops",
      "Roller Skates with Headphones",
      "Bike with More Than One Flag",
      "Playing Music Without Headphones",
      "Costume or Cosplay",
      "Someone Knitting While Walking",
      "Drinking Something Questionable",
      "Off-Brand Segway",
      "Unicyclist",
      "Someone Giving a Tour to Nobody",
    ],
  },
];
