export interface GameTheme {
  id: number;
  name: string;
  freeSpaceLabel?: string;
  labels: string[];
}

export const MOCK_GAME_THEMES: GameTheme[] = [
  {
    id: 0,
    name: "Steelheads Hockey Jerseys",
    freeSpaceLabel: "Steelheads",
    labels: [
      "Anaheim Ducks",
      "Arizona Coyotes",
      "Boston Bruins",
      "Buffalo Sabres",
      "Calgary Flames",
      "Carolina Hurricanes",
      "Chicago Blackhawks",
      "Colorado Avalanche",
      "Columbus Blue Jackets",
      "Dallas Stars",
      "Detroit Red Wings",
      "Edmonton Oilers",
      "Florida Panthers",
      "Los Angeles Kings",
      "Minnesota Wild",
      "Montreal Canadiens",
      "Nashville Predators",
      "New Jersey Devils",
      "New York Islanders",
      "New York Rangers",
      "Ottawa Senators",
      "Philadelphia Flyers",
      "Pittsburgh Penguins",
      "San Jose Sharks",
      "Seattle Kraken",
      "St. Louis Blues",
      "Tampa Bay Lightning",
      "Toronto Maple Leafs",
      "Vancouver Canucks",
      "Vegas Golden Knights",
      "Washington Capitals",
      "Winnipeg Jets",
      "Fictional Team",
      "Historic Team",
      "College Team",
      "AHL/ECHL",
    ],
  },
  {
    id: 1,
    name: "Baseball",
    labels: [
      "Strikeout (swinging)",
      "Strikeout (looking)",
      "Single",
      "Double",
      "Triple",
      "Home Run",
      "Walk",
      "Hit by Pitch",
      "Sacrifice Fly",
      "Sacrifice Bunt",
      "Stolen Base",
      "Caught Stealing",
      "Diving Catch",
      "Double Play",
      "Triple Play",
      "Ground Rule Double",
      "Wild Pitch",
      "Passed Ball",
      "Infield Fly Rule",
      "Pop-up to catcher",
      "Dropped Third Strike",
      "Pitcher Pickoff Attempt",
      "Relief Pitcher Enters",
      "Mound Visit",
      "Player or Coach Ejected",
      "Batter Breaks Bat",
      "Runner Slides into Base",
      "Replay Review",
      "Balk",
      "Fan Interference",
      "Rain Delay",
      "Player Loses a Helmet",
      "Foul Ball Into Dugout",
      "Ball Hits Umpire",
      "Player argues with the umpire",
      "Fan Catches Foul Ball",
      "Mascot Does Something Weird",
      "Wave in the Crowd",
      "Fan on Jumbotron Doing a Dance",
    ],
  },
  {
    id: 2,
    name: "Brewery People Watching",
    labels: [
      "Train",
      "Something Falls",
      "Broken Glass",
      "Bike Gear Inside",
      "Hat from a different Brewery",
      "Shirt from a different Brewery",
      "Actively Brewing",
      "Staff Drinking",
      "Beard Over 6 Inches",
      "Board Game Being Played",
      "Laptop Out",
      "Food Truck",
      "Small Dog (Under 15 lbs.)",
      "Beer Flight",
      "Unattended Child",
      "Drinking Wine",
      "Dog Wearing a Bandana",
      "Photo Shoot",
      "Flannel",
      "Lawn Game in Progress",
      "Man Bun",
      "Dog Eating Human Food",
      "Someone Reading a Book",
      "Moustache",
      "Someone on facetime",
      "Barking Dog",
      "Large Dog (Over 50 lbs.)",
      "Someone Leaving with Beer to go",
      "Party Bus",
      "Baby in a stroller with a dog",
    ],
  },
  {
    id: 3,
    name: "Boise Greenbelt",
    labels: [
      "Barefoot Bicycling",
      "Dog Off Leash",
      "In a Swimsuit, Not Wet",
      "Biking with No Hands",
      "2+ Pieces of BSU Gear",
      "Scooting with Cargo",
      "Someone Playing a Musical Instrument",
      "Dog in a Cart",
      "2+ People on One Vehicle",
      "Surfboard on a Bike",
      "Tie-Dye",
      "Carrying an Inflatable Object",
      "Cowboy Hat",
      "Knee Pads",
      "Roller Skates",
      "Out of Control Children",
      "Screaming Kids",
      "Drinking Something Questionable",
      "Skate Board",
      "Loitering in Middle of the Path",
      "Maintenance Vehicle",
      "People Arguing",
      "Bicycle Cop",
      "One Wheel/Segway",
      "Dog wearing clothes",
    ],
  },
  {
    id: 4,
    name: "Tattoos",
    labels: [
      "Butterfly",
      "Neck tattoo",
      "Matching couple tats",
      "Barbed wire",
      "Script across ribs",
      "Forearm quote",
      "Face tattoo",
      "Wrist infinity symbol",
      "Finger tattoos",
      "Sleeve in progress",
      "Tattoo of an animal",
      "Floral arm piece",
      "Persons Name",
      "Year",
      "Tiny heart or star",
      "Angel wings",
      "Compass or map",
      "Zodiac sign",
      "Roman numerals",
      "Memorial cross",
      "Tattoo behind ear",
      "Tribal design",
      "Tattoo in foreign language",
      "Matching friend tattoos",
      "Pop culture reference",
      "Skull or bones",
      "Tattoo of eyes",
      "Bad Tattoo",
      "Cartoon character",
      "Spelling error",
      "Tattoo on thigh",
    ],
  },
  {
    id: 5,
    name: "Pickle Ball",
    labels: [
      "Whose serve is it?",
      "What’s the score?",
      "Am I a 1 or a 2?",
      "Was that out?",
      "Overhead smash",
      "Dink",
      "Ball called out that was really in",
      "Someone called ball",
      "Someone wearing a skort",
      "A ball in someone’s pocket",
      "2 balls in someone’s pocket",
      "A game of Mortimer",
      "An all guys game",
      "Guys against gals game",
      "A ball hit WAY out",
      "Someone stepped in the kitchen (fault)",
      "Serve landed in the kitchen",
      "A compliment given to opponent",
      "A lob",
      "A Drop Shot",
      "Ace (serve not returned)",
      "Selkirk paddle",
      "Joola paddle",
      "Green pickleball ball",
      "Orange pickleball ball",
      "A pickle (score is 11-0)",
      "Baseball cap",
      "Switching hands",
      "Ball hits the tape",
      "Underhand serve",
      "Bounce serve",
      "Backhand serve",
      "Serve hits the net — lands fair",
      "A person hit by their partner’s ball",
      "A swing and a miss",
      "Pink paddle",
      "Green paddle",
      "Purple paddle",
      "Franklin balls",
      "Gearbox paddle",
      "Wilson shoes",
      "K-Swiss shoes",
      "Under Armour",
      "Nike",
      "Sun visor",
      "Yelling 'Yours!' but neither person takes it",
      "Someone drops a paddle mid-play",
      "Overhead attempt that hits the fence",
      "Someone forgets to switch sides",
      "Someone plays with a bandaged finger",
      "Someone says 'Nice try!' after a total miss",
    ],
  },
  {
    id: 6,
    name: "Anoka",
    labels: [
      "Guy with a mullet",
      "Leather vest with patches",
      "American flag clothing",
      "Biker mustache",
      "Group riding Harleys",
      "Someone drinking from a fishbowl glass",
      "Live music that's too loud",
      "Someone singing karaoke poorly",
      "Matching biker couple outfits",
      "Guy named Randy",
      "Bar with taxidermy",
      "Talking about hunting",
      "Someone who clearly didn’t plan for the weather",
      "Fanny pack",
      "Someone taking shots",
      "Birthday/Bachelorette sash",
      "Couple arguing",
      "Someone falls off a barstool",
      "Sunglasses indoors",
      "Crop top",
      "Bartender with attitude",
      "Drinking Fireball",
      "Someone vaping",
      "Flannel shirt",
      "Overheard 'Back in my day…'",
      "Double fisting beers",
      "Motorcycle Talk",
      "Cowboy boots with shorts",
      "Tattoo of a skull or eagle",
      "Small Dog",
      "Bouncer checking IDs like a cop",
    ],
  },
  {
    id: 7,
    name: "Youth Girls Softball",
    labels: [
      "Cartwheel in the outfield",
      "Eating grass",
      "Picking flowers",
      "Drawing in the dirt",
      "Wearing a helmet in the dugout",
      "Glove on head",
      "Sitting down in the field",
      "Coach yelling encouragement",
      "A run scored on total chaos",
      "Parents yelling 'good eye!'",
      "A ball rolled all the way to the fence",
      "Everyone runs to the ball at once",
      "Player runs the wrong way",
      "A fielder doing the splits",
      "A glove thrown mid-play",
      "Pigtails under a visor",
      "Team huddle chant",
      "A Slide",
      "Fielder waving to the stands",
      "Overthrow",
      "Under-throw",
      "Catcher mask too big for the kid",
      "Coach or umpire tying a shoe",
      "Child in the stands doing cheers",
      "Swing and spin",
      "Throwing the ball *after* the runner is safe",
      "Sunglasses way too big",
      "Face painted with eye black",
      "Snack handed out before the game ends",
    ],
  },
  {
  id: 8,
    name: "Olson's General Store",
    labels: [
        "Magic Clap",
        "Supt. Update",
        "Amazing Staff 'It's the people'",
        "Monti on the Move",
        "Be the light",
        "Annoy Intro",
        "Nature Base",
        "Collaborate",
        "Partnership",
        "Stakeholders",
        "Thank you Horace Mann & Von",
        "Cold Days & Snow Days",
        "Go Big",
        "I can't stop smiling",
        "Over ten minutes",
        "Talk about former supt.",
        "Passing levy",
        "Still making cuts",
        "How many years he has been in the Monticell District",
        "Take Care of yourself & each other",
        "Innovation",
        "Every Kid, Every Day",
        "Safe and healthy culture",
        "Best District ever",
    ],
  },
];
